name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Install system packages
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Restore/Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install project package
        run: |
          devtools::install()
        shell: Rscript {0}

      - name: Render presentation
        run: |
          Rscript render.R

      - name: Remove gitignore files from github-pages folder for deploy
        run: |
          rm -f output/github-pages/.gitignore
          rm -f output/github-pages/**/.gitignore

      - name: Deploy presentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: output/github-pages
