name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v1

      - name: Restore/Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install R packages
        run: |
          install.packages("devtools")
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install project package
        run: |
          devtools::document()
          devtools::install()
        shell: Rscript {0}

      - name: Lint
        run: |
          lintr::lint_package()
        shell: Rscript {0}
